"""Assessment rendering: markdown + JSON."""
from __future__ import annotations

import json

from .models import Assessment

ETHICS = ("_Attribution is an analytic judgment, not proof. This assessment was "
          "generated by a transparent rule-based engine and must be reviewed by a "
          "qualified analyst before any action is taken._")


def to_dict(a: Assessment) -> dict:
    return {
        "case_id": a.case_id,
        "leading": a.leading,
        "confidence": a.confidence.value,
        "hypotheses": [
            {"hypothesis": h.hypothesis, "support": round(h.support, 4),
             "contradiction": round(h.contradiction, 4), "score": round(h.score, 4),
             "matched": [s.label for s in h.matched],
             "contradicting": [s.label for s in h.contradicting]}
            for h in a.hypotheses
        ],
        "ach_matrix": a.matrix,
        "false_flag_indicators": a.false_flag_indicators,
        "raise_confidence": a.raise_confidence,
        "lower_confidence": a.lower_confidence,
        "links": [list(e) for e in a.links],
        "weights": a.weights,
        "custody": a.custody,
    }


def to_json(a: Assessment) -> str:
    return json.dumps(to_dict(a), indent=2)


def to_markdown(a: Assessment) -> str:
    L = [f"# DRAGNET attribution assessment: {a.case_id}", ""]
    verdict = (f"**{a.leading}** with **{a.confidence.value}** confidence" if a.leading
               else f"**Insufficient for attribution** ({a.confidence.value})")
    L += [f"Assessment: {verdict}", ""]
    L += ["## Hypotheses", "", "| Hypothesis | Support | Contradiction | Score |",
          "|---|---|---|---|"]
    for h in a.hypotheses:
        L.append(f"| {h.hypothesis} | {h.support:.2f} | {h.contradiction:.2f} | {h.score:.2f} |")
    hyps = [h.hypothesis for h in a.hypotheses]
    L += ["", "## ACH matrix (C=consistent, I=inconsistent, N=neutral)", "",
          "| Signal | " + " | ".join(hyps) + " |", "|---" * (len(hyps) + 1) + "|"]
    for sig, row in a.matrix.items():
        L.append(f"| `{sig}` | " + " | ".join(row[h] for h in hyps) + " |")
    L += ["", "## Evidence-to-campaign links", ""]
    L += [f"- `{ev}` -> `{sig}` -> {cid}" for ev, sig, cid in a.links] or ["- none"]
    L += ["", "## False-flag indicators", ""]
    L += [f"- {f}" for f in a.false_flag_indicators] or ["- none detected"]
    L += ["", "## What would raise confidence", ""] + [f"- {x}" for x in a.raise_confidence]
    L += ["", "## What would lower confidence", ""] + [f"- {x}" for x in a.lower_confidence]
    L += ["", "## Chain of custody", "", "| seq | action | item | sha256 | entry_hash |",
          "|---|---|---|---|---|"]
    for e in a.custody:
        L.append(f"| {e['seq']} | {e['action']} | {e['item_id']} | "
                 f"{e['item_hash'][:16]}... | {e['entry_hash'][:16]}... |")
    L += ["", ETHICS, ""]
    return "\n".join(L)
